### ISSUE TITLE
Replica upload panic

### ISSUE THREAD

**Issue by darkworon** [darkworon/oakleaf#10]
```
#>: [PSINFO] Main node: 127.0.0.1:8085, uploading replica to the 127.0.0.1:8086...
Uploaded part 5pKJ2cSkg to the node 127.0.0.1:8085
Uploaded part VYF125IzR to the node 127.0.0.1:8086
[INFO] Node 127.0.0.1:8086 sent to me replica of part VYF125IzR
Uploaded part ReK1hcIkR to the node 127.0.0.1:8086
[INFO] Node 127.0.0.1:8086 sent to me replica of part ReK1hcIkR
Uploaded part vHc1hcIkR to the node 127.0.0.1:8086
[INFO] Node 127.0.0.1:8086 sent to me replica of part vHc1hcIkR
[PSINFO] Main node: 127.0.0.1:8085, uploading replica to the 127.0.0.1:8086...
Uploaded part EJcJhcSzg to the node 127.0.0.1:8085
Uploaded part gXcJh5SkR to the node 127.0.0.1:8086
[INFO] Node 127.0.0.1:8086 sent to me replica of part gXcJh5SkR
Uploaded part MMt125SkR to the node 127.0.0.1:8086
[INFO] Node 127.0.0.1:8086 sent to me replica of part MMt125SkR
Uploaded part LppJ25IkR to the node 127.0.0.1:8086
[PSINFO] Main node: 127.0.0.1:8085, uploading replica to the 127.0.0.1:8086...
Uploaded part OLp12cIkg to the node 127.0.0.1:8085
[INFO] Uploaded new file XSKJ2cIzR, 1.pcap
[INFO] Node 127.0.0.1:8086 sent to me replica of part LppJ25IkR
&{<nil>   0 []}
2017/05/04 15:17:17 http: panic serving [::1]:62927: runtime error: invalid memory address or nil pointer dereference
goroutine 269 [running]:
net/http.(*conn).serve.func1(0xc4200d85a0)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0x13abd40, 0x15e5c80)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
oakleaf/cluster/node/server.fileDownloadHandler(0x15c1440, 0xc420108000, 0xc4204dc600)
	/Users/oleg/go/src/oakleaf/cluster/node/server/handlers.go:59 +0x12a
net/http.HandlerFunc.ServeHTTP(0x142bc60, 0x15c1440, 0xc420108000, 0xc4204dc600)
	/usr/local/go/src/net/http/server.go:1942 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc42011e140, 0x15c1440, 0xc420108000, 0xc4204dc600)
	/Users/oleg/go/src/github.com/gorilla/mux/mux.go:114 +0x10c
net/http.serverHandler.ServeHTTP(0xc420188000, 0x15c1440, 0xc420108000, 0xc4204dc300)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc4200d85a0, 0x15c1b80, 0xc4204ecd00)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce
```

**Comment by darkworon** [comment]
Unable to reproduce the issue
