### ISSUE TITLE
File upload error

### ISSUE THREAD

**Issue by darkworon** [darkworon/oakleaf#3]
MacBook-Pro-Oleg:~ oleg$ date;curl -X POST -H "Content-Type: multipart/form-data" -F data=@1.mp3 http://127.0.0.1:8085/file;date
четверг,  4 мая 2017 г. 13:29:01 (MSK)
curl: (52) Empty reply from server
четверг,  4 мая 2017 г. 13:29:01 (MSK)

#>: 2017/05/04 13:29:01 http: panic serving 127.0.0.1:61748: runtime error: invalid memory address or nil pointer dereference
goroutine 13 [running]:
net/http.(*conn).serve.func1(0xc42014c140)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0x13aab60, 0x15e4c80)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
oakleaf/node/server.fileUploadHandler(0x15c0440, 0xc42022c000, 0xc42000a900)
	/Users/oleg/go/src/oakleaf/node/server/server_handlers.go:226 +0x559
net/http.HandlerFunc.ServeHTTP(0x142aa20, 0x15c0440, 0xc42022c000, 0xc42000a900)
	/usr/local/go/src/net/http/server.go:1942 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc4201381e0, 0x15c0440, 0xc42022c000, 0xc42000a900)
	/Users/oleg/go/src/github.com/gorilla/mux/mux.go:114 +0x10c
net/http.serverHandler.ServeHTTP(0xc42016c0b0, 0x15c0440, 0xc42022c000, 0xc42000a700)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc42014c140, 0x15c0b80, 0xc4200165c0)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce

**Comment by darkworon** [comment]
point error on using function 
`func (p *Part) FindNodesForReplication(count int, nl cluster.NodesList) (err error)`
in server_handler fileUploadHandler

**Comment by darkworon** [comment]
Bug was in using file.Part type instead of part.Part everywhere. Fixed
