### ISSUE TITLE
Error opening "/files" url

### ISSUE THREAD

**Issue by darkworon** [darkworon/oakleaf#8]
> #>: 2017/05/04 14:38:48 http: panic serving [::1]:62506: runtime error: invalid memory address or nil pointer dereference
> goroutine 86 [running]:
> net/http.(*conn).serve.func1(0xc420146140)
> 	/usr/local/go/src/net/http/server.go:1721 +0xd0
> panic(0x13abe20, 0x15e6c80)
> 	/usr/local/go/src/runtime/panic.go:489 +0x2cf
> oakleaf/file.(*List).All(0x15f4580, 0x14174f5)
> 	/Users/oleg/go/src/oakleaf/file/filelist.go:50 +0x42
> oakleaf/node/server.fileListHandler(0x15c2440, 0xc42019c2a0, 0xc420194600)
> 	/Users/oleg/go/src/oakleaf/node/server/server_handlers.go:44 +0x7d
> net/http.HandlerFunc.ServeHTTP(0x142bd70, 0x15c2440, 0xc42019c2a0, 0xc420194600)
> 	/usr/local/go/src/net/http/server.go:1942 +0x44
> github.com/gorilla/mux.(*Router).ServeHTTP(0xc420018960, 0x15c2440, 0xc42019c2a0, 0xc420194600)
> 	/Users/oleg/go/src/github.com/gorilla/mux/mux.go:114 +0x10c
> net/http.serverHandler.ServeHTTP(0xc4200a2dc0, 0x15c2440, 0xc42019c2a0, 0xc420194200)
> 	/usr/local/go/src/net/http/server.go:2568 +0x92
> net/http.(*conn).serve(0xc420146140, 0x15c2b80, 0xc42017aa00)
> 	/usr/local/go/src/net/http/server.go:1825 +0x612
> created by net/http.(*Server).Serve
> 	/usr/local/go/src/net/http/server.go:2668 +0x2ce

**Comment by darkworon** [comment]
Fixed in f10a3ae
